### ISSUE TITLE
can't give exception object to mflog.exception method

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mflog#3]
```
# With standard python logging
>>> import logging
>>> try:
...     1/0
... except Exception as e:
...     logging.exception(e)
... 
ERROR:root:division by zero
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero
```

=> ok

```
# With mflog
>>> from mflog import get_logger
>>> x = get_logger("plop")
>>> try:
...     1/0
... except Exception as e:
...     logging.exception(e)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/logging/__init__.py", line 1819, in exception
    error(msg, *args, exc_info=exc_info, **kwargs)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/logging/__init__.py", line 1811, in error
    root.error(msg, *args, **kwargs)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/logging/__init__.py", line 1314, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/logging/__init__.py", line 1421, in _log
    self.handle(record)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/logging/__init__.py", line 1431, in handle
    self.callHandlers(record)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
    hdlr.handle(record)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/logging/__init__.py", line 861, in handle
    self.emit(record)
  File "/home/fab/metwork/mfext/build/opt/python3/lib/python3.5/site-packages/mflog/__init__.py", line 50, in emit
    logger.error(record.msg, *(record.args), **kwargs)
  File "/home/fab/metwork/mfext/build/opt/python3/lib/python3.5/site-packages/structlog/stdlib.py", line 83, in error
    return self._proxy_to_logger("error", event, *args, **kw)
  File "/home/fab/metwork/mfext/build/opt/python3/lib/python3.5/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    method_name, event=event, **event_kw
  File "/home/fab/metwork/mfext/build/opt/python3/lib/python3.5/site-packages/structlog/_base.py", line 192, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
  File "/home/fab/metwork/mfext/build/opt/python3/lib/python3.5/site-packages/mflog/__init__.py", line 88, in _msg_stderr
    self._json(**event_dict)
  File "/home/fab/metwork/mfext/build/opt/python3/lib/python3.5/site-packages/mflog/__init__.py", line 97, in _json
    self._json_logger.msg(json.dumps(event_dict))
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/home/fab/metwork/mfext/build/opt/python3_core/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ZeroDivisionError('division by zero',) is not JSON serializable
```

=> not ok

**Comment by thefab** [comment]
link with #2
